import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { PrismicPreview } from '@prismicio/next';
import { createClient, repositoryName } from '@/prismicio';
import { Navbar } from '@/components/Navbar';
import Footer from '@/components/Footer';
import NetlifyContactForm from '@/components/NetlifyContactForm';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const nav = await client.getSingle('navbar');
  const footer = await client.getSingle('footer');
  return (
    <html lang="fr">
      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar navData={nav.data} />
        {children}
        <Footer footerData={footer.data} />
        <NetlifyContactForm />
      </body>
      <PrismicPreview repositoryName={repositoryName} />
    </html>
  );
}
